# Generated by Django 2.0.1 on 2018-07-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20180729_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
