# Generated by Django 2.0 on 2018-09-22 07:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0004_intrests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studymaterial',
            new_name='Booklet',
        ),
    ]
