# Generated by Django 2.0 on 2018-09-22 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0005_auto_20180922_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intrests',
            new_name='Interests',
        ),
    ]
