# Generated by Django 2.0.1 on 2018-07-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0027_auto_20180618_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_answered_by',
            name='name_of_teacher',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
