# Generated by Django 2.0.1 on 2018-07-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0028_assignment_answered_by_name_of_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_answered_by',
            name='assigner_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
