# Generated by Django 2.0.1 on 2018-07-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0029_assignment_answered_by_assigner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_answered_by',
            name='name_of_teacher',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
